repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  exclude: ^migrations/
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/psf/black
  rev: 21.6b0
  exclude: ^migrations/
  hooks:
  - id: black
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  exclude: ^migrations/
  hooks:
    - id: flake8
      language: python