language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

services:
  - mysql

env:
  - BACKLOG_CONFIG=$TRAVIS_BUILD_DIR/travis/config.yaml

install:
  # Test dependencies
  - pip install 'pytest==3.7.4'
  # Project dependencies
  - pip install -U .
  # Setup database
  - mysql -e 'CREATE DATABASE emg_backlog_2;'

script:
  - emgbacklog.py migrate --database=default

after_success:
  - pip install codacy-coverage
  - python-codacy-coverage -r coverage.xml
