# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='library_strategy',
        ),
        migrations.AddField(
            model_name='run',
            name='library_source',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='library_strategy',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
