# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0002_auto_20171129_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='biome',
            field=models.ForeignKey(db_column='biome_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backlog.Biome', to_field='biome_id'),
        ),
    ]
