# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0003_auto_20171208_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='title',
            field=models.CharField(max_length=4000, null=True),
        ),
    ]
