# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0004_auto_20171218_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_accession', models.CharField(max_length=20, unique=True)),
                ('secondary_accession', models.CharField(max_length=20, unique=True)),
                ('uuid', models.CharField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Submission',
            },
        ),
        migrations.AddField(
            model_name='assemblyjob',
            name='submission_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backlog.Submission'),
        ),
    ]
