# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0006_auto_20180116_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='uuid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
