# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0009_submission_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assemblyjob',
            name='new_ena_study_prima_accession',
        ),
        migrations.RemoveField(
            model_name='assemblyjob',
            name='new_ena_study_secon_accession',
        ),
    ]
