# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-31 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('backlog', '0011_auto_20180116_1334'), ('backlog', '0012_auto_20180116_1335'), ('backlog', '0013_auto_20180116_1337'), ('backlog', '0014_auto_20180116_1348'), ('backlog', '0015_auto_20180116_1350'), ('backlog', '0016_auto_20180116_1350'), ('backlog', '0017_auto_20180116_1355'), ('backlog', '0018_remove_submission_created'), ('backlog', '0019_submission_created')]

    dependencies = [
        ('backlog', '0010_auto_20180116_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='created_at',
        ),
        migrations.AddField(
            model_name='submission',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
