# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 13:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0010_auto_20180116_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 16, 13, 34, 24, 310833, tzinfo=utc)),
        ),
    ]
