# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0011_auto_20180116_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
