# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 13:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0013_auto_20180116_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='created_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2018, 1, 16, 13, 48, 55, 869916, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
