# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0014_auto_20180116_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='created_at',
        ),
        migrations.AddField(
            model_name='submission',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
