# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 13:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0016_auto_20180116_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 1, 16, 13, 55, 59, 811240, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
