# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0017_auto_20180116_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='created',
        ),
    ]
