# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0018_remove_submission_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
