# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0019_submission_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
