# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0020_auto_20180116_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyjob',
            name='runs',
            field=models.ManyToManyField(blank=True, related_name='assemblyjobs', through='backlog.RunAssemblyJob', to='backlog.Run'),
        ),
        migrations.AlterUniqueTogether(
            name='runassemblyjob',
            unique_together=set([('run', 'assembly_job')]),
        ),
    ]
