# Generated by Django 2.0.3 on 2018-04-10 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0021_auto_20180117_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submitter',
            fields=[
                ('webin_id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, verbose_name="ENA's submission account id")),
                ('registered', models.BooleanField(default=False, verbose_name="A copy of ENA's ROLE_METAGENOME_SUBMITTER flag. Set to True if submitter is registered with EMG.")),
                ('consent_given', models.BooleanField(default=False, verbose_name="A copy of ENA's ROLE_METAGENOME_ANALYSIS flag. Set to True if submitter gave permission to access and analyse their private data.")),
                ('email_address', models.CharField(max_length=200, verbose_name='Submitters email address.')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('surname', models.CharField(max_length=50, null=True)),
                ('first_created', models.DateField(verbose_name="A copy of ENA's FIRST_CREATED flag.")),
            ],
            options={
                'db_table': 'Submitter',
            },
        ),
        migrations.AddField(
            model_name='study',
            name='submitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backlog.Submitter'),
        ),
        migrations.AddField(
            model_name='submission',
            name='submitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backlog.Submitter'),
        ),
    ]
