# Generated by Django 2.0.3 on 2018-05-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0023_assembly_ena_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
