# Generated by Django 2.0.3 on 2018-06-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0024_run_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='biome_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='run',
            name='compressed_data_size',
            field=models.BigIntegerField(help_text='Sum of filesizes of compressed input. (bytes)', null=True),
        ),
    ]
