# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0026_auto_20180604_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='primary_accession',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='study',
            unique_together=set([('primary_accession', 'secondary_accession')]),
        ),
    ]
