# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 02:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0027_auto_20180604_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='biome',
            field=models.ForeignKey(blank=True, db_column='biome_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backlog.Biome', to_field='biome_id'),
        ),
        migrations.AlterField(
            model_name='run',
            name='compressed_data_size',
            field=models.BigIntegerField(blank=True, help_text='Sum of filesizes of compressed input. (bytes)', null=True),
        ),
    ]
