# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0028_auto_20180614_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyjob',
            name='directory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
