# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 22:02
from __future__ import unicode_literals

from django.db import migrations, models


def populate_assembly_upload_status(apps, schema_editor):
    Status = apps.get_model('backlog', 'AssemblyJobStatus')
    sts = (
        (1, "pending"),
        (2, "running"),
        (3, "stats required"),
        (4, "compression required"),
        (5, "finished assembling"),
        (6, "not uploaded"),
        (7, "uploaded"),
        (8, "(ENA) archive failed"),
        (9, "(ENA) processing failed"),
        (10, "(ENA) private"),
        (11, "(ENA) public"),
    )
    for id, desc in sts:
        s = Status(id=id, description=desc)
        s.save()


class Migration(migrations.Migration):
    dependencies = [
        ('backlog', '0029_assemblyjob_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblyjobstatus',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.RunPython(populate_assembly_upload_status)
    ]
