# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-15 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0030_auto_20180626_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyjob',
            name='estimated_peak_mem',
            field=models.BigIntegerField(help_text='Estimated peak memory usage of the assembler, in megabytes.', null=True),
        ),
        migrations.AddField(
            model_name='assemblyjob',
            name='requester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backlog.Submitter'),
        ),
        migrations.AddField(
            model_name='run',
            name='sample_primary_accession',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
