# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-15 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0031_auto_20181015_0933'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Submitter',
            new_name='User',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
