# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-16 11:46
from __future__ import unicode_literals

from django.db import migrations

def insert_annotation_job_fixtures(apps, schema_editor):
    AnnotationStatus = apps.get_model('backlog', 'AnnotationStatus')
    statuses = ['SCHEDULED', 'ON_HOLD', 'RUNNING', 'COMPLETED', 'FAILED', 'NO_DATA', 'BLACKLISTED', 'CANCELLED BY USER', 'UPLOADED', 'USER_NOTIFIED']
    for status in statuses:
        AnnotationStatus(description=status).save()


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0032_auto_20181015_0938'),
    ]

    operations = [
        migrations.RunPython(insert_annotation_job_fixtures)
    ]
