# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-06 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# backlog.migrations.0033_auto_20181016_1146
# backlog.migrations.0042_auto_20181123_1042

def add_annotation_status(apps, schema_editor):
    Status = apps.get_model('backlog', 'AnnotationJobStatus')
    s = Status(description='RESULTS_SYNCED')
    s.save()

def insert_annotation_job_fixtures(apps, schema_editor):
    AnnotationJobStatus = apps.get_model('backlog', 'AnnotationJobStatus')
    statuses = ['SCHEDULED', 'ON_HOLD', 'RUNNING', 'COMPLETED', 'FAILED', 'NO_DATA', 'BLACKLISTED', 'CANCELLED BY USER', 'UPLOADED', 'USER_NOTIFIED']
    for status in statuses:
        AnnotationJobStatus(description=status).save()


class Migration(migrations.Migration):

    replaces = [('backlog', '0033_auto_20181016_1146'), ('backlog', '0034_auto_20181016_1232'), ('backlog', '0035_userrequest_rt_ticket'), ('backlog', '0036_auto_20181101_1525'), ('backlog', '0037_auto_20181101_1536'), ('backlog', '0038_auto_20181101_1542'), ('backlog', '0039_auto_20181101_1603'), ('backlog', '0040_auto_20181122_1436'), ('backlog', '0041_auto_20181122_1444'), ('backlog', '0042_auto_20181123_1042'), ('backlog', '0043_auto_20181123_1127'), ('backlog', '0044_auto_20181123_1241'), ('backlog', '0045_auto_20181123_1257'), ('backlog', '0046_auto_20181128_1343'), ('backlog', '0047_annotationjob_directory')]

    dependencies = [
        ('backlog', '0032_auto_20181015_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='backlog.User')),
                ('rt_ticket', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'UserRequest',
            },
        ),
        migrations.RemoveField(
            model_name='annotationjob',
            name='user',
        ),
        migrations.RemoveField(
            model_name='assemblyjob',
            name='user',
        ),
        migrations.AddField(
            model_name='annotationjob',
            name='request',
            field=models.ForeignKey(db_column='request_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backlog.UserRequest'),
        ),
        migrations.AddField(
            model_name='assemblyjob',
            name='request_id',
            field=models.ForeignKey(db_column='request_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backlog.UserRequest'),
        ),
        migrations.RenameModel(
            old_name='AnnotationStatus',
            new_name='AnnotationJobStatus',
        ),
        migrations.AlterModelTable(
            name='annotationjobstatus',
            table='AnnotationJobStatus',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='runannotationjob',
            unique_together=set([('run', 'annotation_job')]),
        ),
        migrations.RunPython(add_annotation_status),
        migrations.RenameField(
            model_name='annotationjob',
            old_name='exec_status',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='AnnotationJob',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backlog.AnnotationJobStatus'),
        ),
        migrations.AlterField(
            model_name='annotationjob',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backlog.AnnotationJobStatus'),
        ),
        migrations.AlterField(
            model_name='annotationjob',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backlog.AnnotationJobStatus'),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='primary_accession',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='primary_accession',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='secondary_accession',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='annotationjob',
            name='directory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(insert_annotation_job_fixtures)
    ]
