# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0034_auto_20181016_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='rt_ticket',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
