# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-01 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0036_auto_20181101_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotationjob',
            old_name='request_id',
            new_name='request',
        ),
    ]
