# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-01 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0037_auto_20181101_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='rt_ticket',
            field=models.IntegerField(unique=True),
        ),
    ]
