# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-22 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0039_auto_20181101_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrequest',
            old_name='webin_id',
            new_name='user_id',
        ),
        migrations.AlterUniqueTogether(
            name='runannotationjob',
            unique_together=set([('run', 'annotation_job')]),
        ),
    ]
