# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-22 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0040_auto_20181122_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrequest',
            old_name='user_id',
            new_name='user',
        ),
    ]
