# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 22:02
from __future__ import unicode_literals

from django.db import migrations, models


def add_annotation_status(apps, schema_editor):
    Status = apps.get_model('backlog', 'AnnotationJobStatus')
    s = Status(description='RESULTS_SYNCED')
    s.save()


class Migration(migrations.Migration):
    dependencies = [
        ('backlog', '0041_auto_20181122_1444'),
    ]

    operations = [
        migrations.RunPython(add_annotation_status)
    ]
