# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-23 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0042_auto_20181123_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='AnnotationJob',
            name='exec_status',
            field=models.ForeignKey(to='backlog.AnnotationJobStatus')
        )
    ]
