# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-23 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('backlog', '0043_auto_20181123_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotationjob',
            old_name='exec_status',
            new_name='status',
        ),
    ]
