# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-23 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0044_auto_20181123_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationjob',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backlog.AnnotationJobStatus'),
        ),
    ]
