# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0045_auto_20181123_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembly',
            name='primary_accession',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='primary_accession',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='secondary_accession',
            field=models.CharField(max_length=20),
        ),
    ]
