# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-18 16:50
from __future__ import unicode_literals

from django.db import migrations
import sys

# FIX FOR MIGRATIONS 0033 AND 0048 WHERE THE TARGET DATABASE WAS NOT SET CORRECTLY
def insert_missing_annotation_job_status_fixtures(apps, schema_editor):
    database = 'default'
    try:
        i = sys.argv.index('--database')
        database = sys.argv[i + 1]
    except ValueError:
        pass

    AnnotationJobStatus = apps.get_model('backlog', 'AnnotationJobStatus')
    statuses = ['SCHEDULED', 'ON_HOLD', 'RUNNING', 'COMPLETED', 'FAILED', 'NO_DATA', 'BLACKLISTED', 'CANCELLED BY USER',
                'UPLOADED', 'USER_NOTIFIED', 'QC_NOT_PASSED', 'UNABLE_TO_PROCESS', 'UNKNOWN', 'FETCHING_RAW_FILES', 'FETCHED_RAW_FILES', 'SYNCING', 'SYNCED',
               'SANITY_CHECKED']
    for status in statuses:
        try:
            if len(AnnotationJobStatus.objects.using(database).filter(description=status)) == 0:
                AnnotationJobStatus(description=status).save(using=database)
        except Exception as e:
            print(e)


class Migration(migrations.Migration):
    dependencies = [
        ('backlog', '0048_auto_20181218_1557'),
    ]

    operations = [
        migrations.RunPython(insert_missing_annotation_job_status_fixtures)
    ]
