# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-12 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0051_assemblyjob_cram_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationjob',
            name='runs',
            field=models.ManyToManyField(blank=True, related_name='annotationjobs', through='backlog.RunAnnotationJob', to='backlog.Run'),
        ),
    ]
