# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-25 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0053_assembly_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assemblyjob',
            old_name='cram_uploaded',
            new_name='bam_uploaded',
        ),
    ]
