# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-15 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0054_auto_20190225_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='library_strategy',
            field=models.CharField(db_index=True, max_length=150, null=True),
        ),
    ]
