# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-15 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0055_auto_20190315_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='base_count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='read_count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
