# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-28 10:40
from __future__ import unicode_literals

from django.db import migrations
import sys

def insert_sync_failed_status_fixtures(apps, schema_editor):
    database = 'default'
    try:
        i = sys.argv.index('--database')
        database = sys.argv[i + 1]
    except ValueError:
        pass

    AnnotationJobStatus = apps.get_model('backlog', 'AnnotationJobStatus')
    res = AnnotationJobStatus.objects.using(database).filter(description='SYNC-FAILED')
    if len(res) == 0:
        try:
            AnnotationJobStatus(description='SYNC-FAILED').save(using=database)
        except Exception as e:
            print(e)

class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0057_auto_20190315_1713'),
    ]

    operations = [
        migrations.RunPython(insert_sync_failed_status_fixtures)
    ]

