# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-12 09:12
from __future__ import unicode_literals

import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0058_auto_20190328_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='biome',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='biome',
            name='id',
        ),
        migrations.AlterField(
            model_name='biome',
            name='biome_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='biome',
            field=models.ForeignKey(blank=True, db_column='biome_id', null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, to='backlog.Biome'),
        ),
    ]
