# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-29 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0059_auto_20190412_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='biome',
            field=models.ForeignKey(blank=True, db_column='biome_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backlog.Biome'),
        ),
    ]
