# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-05-30 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sys

def insert_cleaned_status_fixtures(apps, schema_editor):
    database = 'default'
    try:
        i = sys.argv.index('--database')
        database = sys.argv[i + 1]
    except ValueError:
        pass

    AnnotationJobStatus = apps.get_model('backlog', 'AnnotationJobStatus')
    res = AnnotationJobStatus.objects.using(database).filter(description='CLEANED')
    if len(res) == 0:
        try:
            AnnotationJobStatus(description='CLEANED').save(using=database)
        except Exception as e:
            print(e)


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0060_assembly_biome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='biome_validated',
        ),
        migrations.AddField(
            model_name='assembly',
            name='inferred_biome',
            field=models.ForeignKey(blank=True, db_column='inferred_biome_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inferred_assembly_biome', to='backlog.Biome'),
        ),
        migrations.AddField(
            model_name='run',
            name='inferred_biome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inferred_run_biome', to='backlog.Biome'),
        ),
        migrations.RunPython(insert_cleaned_status_fixtures, reverse_code=lambda apps, schema_editor: '')
    ]
