# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-06-24 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0061_biome_inference_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationjob',
            name='attempt',
            field=models.IntegerField(default=0),
        )
    ]
