# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-17 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0062_auto_20190624_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorAnnotationJobs',
            fields=[
                ('secondary_accession', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('rt_ticket', models.IntegerField(default=0)),
                ('created', models.DateTimeField()),
                ('priority', models.IntegerField()),
                ('public', models.BooleanField(default=False)),
                ('jobs_in_study', models.IntegerField()),
                ('scheduled_jobs', models.IntegerField()),
                ('running_jobs', models.IntegerField()),
                ('failed_jobs', models.IntegerField()),
                ('completed_jobs', models.DecimalField(decimal_places=3, max_digits=27)),
                ('syncing_jobs', models.IntegerField()),
                ('synced_jobs', models.IntegerField()),
                ('uploaded_jobs', models.IntegerField()),
                ('user_notified', models.BooleanField(default=False)),
                ('number_of_biomes', models.IntegerField()),
                ('biome_tagging_complete', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'monitor annotation jobs',
                'db_table': 'monitor_annotation_jobs',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='assembly',
            options={'verbose_name_plural': 'assemblies'},
        ),
        migrations.AlterModelOptions(
            name='assemblyjobstatus',
            options={'verbose_name_plural': 'assembly job statuses'},
        ),
        migrations.AlterModelOptions(
            name='runassembly',
            options={'verbose_name_plural': 'run assemblies'},
        ),
        migrations.AlterModelOptions(
            name='study',
            options={'verbose_name_plural': 'studies'},
        ),
        migrations.AlterField(
            model_name='assemblyannotationjob',
            name='assembly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assemblyannotationjobs', to='backlog.Assembly'),
        ),
    ]
