# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-20 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0063_auto_20191120_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblyannotationjob',
            name='assembly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assemblyannotationjobs', to='backlog.Assembly'),
        ),
    ]
