# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-05 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    def add_new_pipeline_version(apps, schema_editor):
        Pipeline = apps.get_model('backlog', 'Pipeline')
        Pipeline(version=5.0).save()

    dependencies = [
        ('backlog', '0064_auto_20191120_1535'),
    ]

    operations = [
        migrations.RunPython(add_new_pipeline_version)
    ]
