# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-02 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def add_assembly_types(apps, schema_editor):
    """
    Add assembly types:
    - primary metagenome
    - binned Metagenome
    - Metagenome-Assembled Genome (MAG)
    - metatranscriptome
    - INSDC style metagenome assemblies
    """
    AssemblyType = apps.get_model("backlog", "AssemblyType")
    for type in ["primary metagenome", "binned metagenome", "Metagenome-Assembled Genome (MAG)",
                "metatranscriptome", "INSDC style metagenome assemblies"]:
        AssemblyType.objects.get_or_create(assembly_type=type)


def remove_assembly_types(apps, schema_editor):
    """
    Remove assembly types
    """
    AssemblyType = apps.get_model("backlog", "AssemblyType")
    for type in ["primary metagenome", "binned metagenome", "Metagenome-Assembled Genome (MAG)",
                 "metatranscriptome", "INSDC style metagenome assemblies"]:
        try:
            AssemblyType.objects.get(assembly_type=type).delete()
        except AssemblyType.DoesNotExist:
            pass


class Migration(migrations.Migration):
    dependencies = [
        ('backlog', '0066_auto_20200521_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assembly_type', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'AssemblyType',
            },
        ),
        migrations.AddField(
            model_name='assembly',
            name='assembly_type',
            field=models.ForeignKey(blank=True, db_column='assembly_type_id', null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, to='backlog.AssemblyType'),
        ),
        migrations.RunPython(add_assembly_types, reverse_code=remove_assembly_types)
    ]
