# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-15 14:53
from __future__ import unicode_literals

import sys

from django.db import migrations

def add_status(apps, schema_editor):
    database = 'default'
    try:
        i = sys.argv.index('--database')
        database = sys.argv[i + 1]
    except ValueError:
        pass

    AnnotationJobStatus = apps.get_model('backlog', 'AnnotationJobStatus')
    AnnotationJobStatus.objects.using(database).get_or_create(description='FINISHED')


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0068_annotationjob_result_status'),
    ]

    operations = [
        migrations.RunPython(add_status)
    ]
