# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-13 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0069_auto_20200915_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyjobresult',
            name='coverage_depth',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
