# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-21 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0070_assemblyjobresult_coverage_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyannotationjob',
            name='protein_db',
            field=models.BooleanField(default=False, verbose_name='Boolean field to mark was assembly from Job added to protein DB or not'),
        ),
    ]
