# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-22 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0071_assemblyannotationjob_protein_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblyannotationjob',
            name='protein_db',
            field=models.BooleanField(default=False, verbose_name='True if the linked assembly was added to the protein DB'),
        ),
    ]
