# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-22 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0072_auto_20210422_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblyannotationjob',
            name='protein_db',
            field=models.IntegerField(choices=[(1, 'Retrofitting finished without errors'), (0, 'Retrofitting was not run OR failed by unknown reason'), (2, 'There is no faa fasta file with predicted proteins'), (3, 'Invalid path, failed to find the results folder'), (4, 'Can not detect directory in EMG table'), (5, 'Study was suppressed by ENA')], default=0),
        ),
    ]
