# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-13 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0073_assemblyproteindb'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyproteindb',
            name='assembly_id_pdb',
            field=models.IntegerField(null=True, verbose_name='id_pdb'),
        ),
    ]
