# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-23 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0074_assemblyproteindb_assembly_id_pdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblyproteindb',
            name='fail_reason',
            field=models.IntegerField(blank=True, choices=[(1, 'Missing protein fasta file'), (2, 'Invalid fasta file path'), (3, 'Assembly results directory is missing'), (4, 'Suppressed assembly'), (5, 'Incorrect number of sequences for MGYC.fasta'), (6, 'Incorrect number of sequences for MGYP.fasta'), (7, 'Incorrect number of records for metadata'), (8, 'Incorrect MGYC and MGYP but metadata is OK'), (9, 'Incorrect number of sequences for MGYC.fasta and metadata table/file'), (10, 'Incorrect number of sequences for MGYP.fasta and metadata table/file'), (11, 'Incorrect number of sequences for MGYC, MGYP and metadata')], null=True, verbose_name='fail_reason'),
        ),
        migrations.AlterField(
            model_name='assemblyproteindb',
            name='pipeline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backlog.Pipeline'),
        ),
    ]
