# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-08-12 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0076_auto_20210812_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assemblyannotationjob',
            name='protein_db',
        ),
    ]
