backlog:
  databases:
    default:
      ENGINE: 'django.db.backends.mysql'
      NAME: 'emg_backlog_2'
      USER: 'travis'
      HOST: localhost
      PORT: 3306
      DB: 'emg_backlog_2'
    dev:
      ENGINE: 'django.db.backends.mysql'
      NAME: 'emg_backlog_2'
      USER: 'travis'
      HOST: localhost
      PORT: 3306
      DB: 'emg_backlog_2'
    prod:
      ENGINE: 'django.db.backends.mysql'
      NAME: 'emg_backlog_2'
      USER: 'travis'
      HOST: localhost
      PORT: 3306
      DB: 'emg_backlog_2'